### ISSUE TITLE
Can't launch with Xcode 11

### ISSUE THREAD

**Issue by Watson1978** [Watson1978/OpenGithub#4]
```
$ xcodebuild -version
Xcode 11.0
Build version 11A420a
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

$ ruby ./OpenGithubHelper/open_xcode_file_on_github.rb
execution error: Xcodeでエラーが起きました: AppleEventのハンドラで誤りが起きました。 (-10000)
Traceback (most recent call last):
	1: from ./OpenGithubHelper/open_xcode_file_on_github.rb:8:in `<main>'
/Users/watson/prj/OpenGithub/OpenGithubHelper/xcode_helper.rb:38:in `project_root': Can't detect project root path (RuntimeError)
```

Related to http://openradar.appspot.com/radar?id=4945935847129088

**Comment by Watson1978** [comment]
Seems this issue was solved at Xcode 11.2
